MA-13067-16 [#imx-1215] Fix QNX build error involved by DEQP patch
Fix QNX build error involved by Below DEQP patch
commit cda85c1fdf9780f52a866b08166b9cafca905fc0
MA-13067-2 [#imx-1215] Fix dEQP-VK.robustness* CTS fail on 8qm

Build error log:
error: 'calleeParmVregId' may be used uninitialized in this
function [-Werror=maybe-uninitialized]
calleeParmVregSym = VIR_Shader_FindSymbolByTempIndex(pShader, calleeParmVregId + j);
cc1: all warnings being treated as errors

Change-Id: I8b41113c291d2a22a84bdcf42e7f96b373445e8d
Signed-off-by: Richard Liu <xuegang.liu@nxp.com>