MA-8739 [#imx-402] fix video playback fail issue on 6sx_evk board
When play one h264 video 2d blit report gcvSTATUS_NOT_ALIGNED error,
root cause is the buffer Address[1] not meet the aligned request,
update the aligment limitation on android, the video can play and
don't see any side effect.

Buffer info:
Width = 480, Height = 260
Format = gcvSURF_YV12
Address[0] = 0x1d029b80
Address[1] = 0x1d04fce0
Address[2] = 0x1d048300

Fail error:
ONERROR: status=-20 @ gco2D_FilterBlitEx2(4287)
ONERROR: status=-20 @ g2d_blit_2d(1897)
g2d_blit_2d: fail with status -20

Date: Feb 16, 2017
Signed-off-by: Richard Liu <xuegang.liu@nxp.com>
(cherry picked from commit 5fc4916ef931994c1402f39906e9de9c365fb6cd)